---
title: "Visualization_2"
author: "Kimberly Lopez"
date: "2024-10-01"
output: github_document
---

```{r}
library(tidyverse)
library ( patchwork)
```

# Visualization 2

We’ll still work with NOAA weather data, which is loaded using the same code as in Vis. 1
```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USW00022534", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2021-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = case_match(
      id, 
      "USW00094728" ~ "CentralPark_NY", 
      "USW00022534" ~ "Molokai_HI",
      "USS0023B17S" ~ "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) |>
  select(name, id, everything())
```

# Labels 
Starting with scatterplot, but use labs function to label axis names

```{r}
weather_df |> 
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = .5) + 
  labs(
    title = "Temperature plot",
    x = "Minimum daily temperature (C)",
    y = "Maxiumum daily temperature (C)",
    color = "Location",
    caption = "Weather data from the rnoaa package for three stations"
  )
```

# Scales
